### ISSUE TITLE
Potentially incorrect store command

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#13]
Check to ensure the current setup where the magic store has the "r" command to research an item and the library "bookstore" "r" command researches a spell ... seems like it might be backwards.

**Comment by Gurbintroll** [comment]
I can see what you mean from a thematic point of view. However from a gameplay point of view you can buy all the different magic books at the library and there's one in every town (even Nir), whereas there isn't always a magic shop in town and while it does sell *some* books it doesn't sell all of them.

So having the learn spell command be in the library makes sense from a gameplay angle, because that's where you will be when you get access to new spells.

I suppose from a thematic point of view the library is also "neutral" between mage-types and priest-types. It would be weird if priests had to go to the magic shop to learn new divine spells.
